"""AegisCore — Threat Correlation Engine"""
import json
import os
import logging
from datetime import datetime, timedelta
from app.models.db import db, Alert, Incident
from extensions import socketio

logger = logging.getLogger(__name__)

# Default Correlation Rules
DEFAULT_RULES = [
    {
        "id": "rule_recon_apt",
        "name": "APT Reconnaissance Pattern",
        "description": "Recon + Fuzzers/DoS from same IP within window.",
        "condition": {
            "categories": ["Reconnaissance", "Fuzzers", "DoS", "Analysis"],
            "min_count": 3,
            "window_minutes": 10
        },
        "action": {
            "severity": "high"
        }
    },
    {
        "id": "rule_sustained_dos",
        "name": "Sustained DoS Campaign",
        "description": "Multiple DoS events from same IP.",
        "condition": {
            "categories": ["DoS"],
            "min_count": 3,
            "window_minutes": 10
        },
        "action": {
            "severity": "critical"
        }
    }
]

class CorrelationEngine:
    def __init__(self):
        self.rules = self._load_rules()
        
    def _load_rules(self):
        # Load from config or use defaults
        config_path = os.path.join(os.path.dirname(__file__), 'correlation_rules.json')
        if os.path.exists(config_path):
            try:
                with open(config_path, 'r') as f:
                    return json.load(f)
            except Exception as e:
                logger.error(f"Failed to load correlation rules: {e}")
        return DEFAULT_RULES

    def evaluate_recent_alerts(self):
        """Scans alerts in the sliding window and groups them by source IP to detect patterns."""
        window_start = datetime.utcnow() - timedelta(minutes=10)
        
        # Only look at un-incidenced alerts
        recent_alerts = Alert.query.filter(
            Alert.timestamp >= window_start,
            Alert.incident_id == None,
            Alert.source_ip != None
        ).all()
        
        if not recent_alerts:
            return
            
        # Group by IP
        ip_groups = {}
        for alert in recent_alerts:
            if alert.source_ip not in ip_groups:
                ip_groups[alert.source_ip] = []
            ip_groups[alert.source_ip].append(alert)
            
        incidents_created = 0
            
        for ip, alerts in ip_groups.items():
            if len(alerts) < 3:
                continue # Skip IPs with too few events
                
            categories_present = set(a.category for a in alerts)
            
            # Evaluate against rules
            for rule in self.rules:
                cond = rule['condition']
                # Check if categories match the rule
                matching_alerts = [a for a in alerts if a.category in cond['categories']]
                
                if len(matching_alerts) >= cond['min_count']:
                    # Trigger Incident
                    incident = Incident(
                        title=f"Correlated Threat: {rule['name']}",
                        description=f"Automatically generated by Correlation Engine. Triggered by {len(matching_alerts)} alerts from {ip} matching rule '{rule['id']}'.\n\n{rule['description']}",
                        severity=rule['action']['severity'],
                        status='open'
                    )
                    db.session.add(incident)
                    db.session.flush() # Get incident ID
                    
                    # Link alerts to incident
                    for a in matching_alerts:
                        a.incident_id = incident.id
                        
                    # Remove used alerts from the group so they aren't double-correlated
                    for a in matching_alerts:
                        alerts.remove(a)
                        
                    incidents_created += 1
                    
                    socketio.emit('new_incident', incident.to_dict())
                    break # Stop evaluating rules for this IP once an incident is created
                    
        if incidents_created > 0:
            db.session.commit()
            logger.info(f"Correlation Engine generated {incidents_created} new incidents.")
